/* eslint-disable @next/next/no-img-element */
'use cache';
// COMPONENTS
import { Separator } from '@/src/components/ui/separator';
// CONSTANTS
import { LAST_LEGAL_UPDATE_DATE as date } from '@/src/utils/constant';
import Link from 'next/link';

const TermsAndConditionsPage = async () => {
  return (
    <div className='flex flex-col w-full min-h-screen bg-background'>
      <div className='container mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 lg:py-20'>
        <div className='flex flex-col lg:flex-row items-start lg:items-center justify-between gap-8 lg:gap-12'>
          <div className='flex-1 flex flex-col gap-4'>
            <h1 className='text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight'>
              Terms and Conditions
            </h1>
            <p className='text-lg sm:text-xl text-muted-foreground max-w-2xl'>
              Please read these Terms carefully before using our Service. By
              accessing or using our Service, you agree to be bound by these
              Terms.
            </p>
          </div>
          <div className='shrink-0 w-full hidden lg:block lg:w-auto lg:max-w-md'>
            <div className='flex w-full h-64 sm:h-80 lg:h-96 items-center justify-center rounded-xl'>
              <img
                src='/illustrations/lawyer-light.svg'
                alt='Legal illustration'
                className='w-full h-full object-contain dark:hidden'
              />
              <img
                src='/illustrations/lawyer-dark.svg'
                alt='Legal illustration'
                className='w-full h-full object-contain hidden dark:block'
              />
            </div>
          </div>
        </div>
      </div>

      <div className='container mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 lg:py-20'>
        <div className='flex flex-col gap-12 sm:gap-16'>
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Introduction
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                These Terms and Conditions (&quot;Terms&quot;) govern your
                access to and use of the Press0 WhatsApp AI Agent
                (&quot;Service&quot;). By initiating a conversation with the
                Service or otherwise using it, you acknowledge that you have
                read, understood, and agree to be bound by these Terms and our
                <Link href='/privacy-policy' className='text-blue-400'>
                  {' '}
                  Privacy Policy
                </Link>
                .
              </p>
              <p>
                If you do not agree with any part of these Terms, you must
                discontinue use of the Service immediately.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Acceptance of Terms
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed '>
              <p>
                By accessing or using the Service, you consent to the processing
                of your information and agree that these Terms constitute a
                legally binding agreement between you and Press0.
              </p>
              <p>
                These Terms apply to all users of the Service regardless of
                purpose, including individuals, businesses, and third parties
                who access the Service through your WhatsApp account.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Service Description
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                The Service provides automated responses, assistance, and
                interactions through WhatsApp using artificial intelligence
                technologies. The Service is not monitored by a human, may
                generate incorrect or incomplete information, and is provided
                solely for general informational purposes.
              </p>
              <p>
                Press0 does not guarantee the accuracy, completeness,
                reliability, or suitability of any output generated by the
                Service.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              No Account or Authentication
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                The Service does <span className='font-semibold'>not</span>{' '}
                include a login system, password, or identity-verification
                mechanism of any kind. Accordingly:
              </p>
              <ul className='list-disc pl-5 space-y-2'>
                <li>
                  Any individual who sends a message from your WhatsApp number
                  will be deemed an authorized user.
                </li>
                <li>
                  Press0 is not responsible for unauthorized, accidental, or
                  fraudulent use of your WhatsApp number.
                </li>
                <li>
                  You are solely responsible for securing access to your
                  WhatsApp account and device.
                </li>
              </ul>
              <p>
                If you suspect unauthorized use, you must stop using the Service
                immediately.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              User Responsibilities
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>You agree that you will:</p>
              <ul className='list-disc pl-5 space-y-2'>
                <li>Use the Service only for lawful purposes.</li>
                <li>
                  Not share sensitive, confidential, financial, medical, or
                  personal data with the Service.
                </li>
                <li>
                  Not attempt to misuse, overload, disrupt, or reverse-engineer
                  the Service.
                </li>
                <li>
                  Ensure compliance with all applicable laws and regulations
                  when using the Service.
                </li>
              </ul>
              <p>
                You understand that any content you send may be processed by
                third-party providers for the purpose of generating responses.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Data Collection and Use
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                By using the Service, you consent to the collection, processing,
                and storage of the messages, media, and metadata you send to the
                WhatsApp AI Agent. Such data may be used for:
              </p>
              <ul className='list-disc pl-5 space-y-2'>
                <li>Delivering and improving the Service</li>
                <li>Debugging, analytics, and security</li>
                <li>Enhancing AI model performance</li>
                <li>Abuse detection and prevention</li>
              </ul>
              <p>
                The Service does not access messages outside of the chat you
                initiate. Data transmission through WhatsApp is subject to
                WhatsApp’s system, encryption, and policies, which Press0 does
                not control.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Third-Party Services
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                The Service relies on third-party platforms and providers
                including, but not limited to:
              </p>
              <ul className='list-disc pl-5 space-y-2'>
                <li>WhatsApp (for messaging delivery)</li>
                <li>AI model providers (for automated responses)</li>
                <li>Cloud infrastructure and data storage services</li>
              </ul>
              <p>
                Press0 is not responsible for outages, changes, data handling,
                or actions taken by any third-party provider.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Prohibited Uses
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>You agree not to use the Service:</p>
              <ul className='list-disc pl-5 space-y-2'>
                <li>For any illegal, harmful, or fraudulent activity</li>
                <li>To impersonate any person or entity</li>
                <li>
                  To transmit harmful content, malware, or unsolicited
                  promotions
                </li>
                <li>
                  To violate the intellectual property or privacy rights of
                  others
                </li>
                <li>To attempt unauthorized access to Press0 infrastructure</li>
              </ul>
              <p>
                Any violation of these Terms may result in immediate termination
                of access.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Intellectual Property
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                All rights, title, and interest in and to the Service—including
                content, software, trademarks, and related materials—are owned
                by Press0 or its licensors.
              </p>
              <p>
                You receive a limited, revocable, non-exclusive license to use
                the Service for personal, non-commercial purposes. You may not
                copy, modify, distribute, reverse-engineer, or create derivative
                works of the Service.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              AI-Generated Output
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>You acknowledge that:</p>
              <ul className='list-disc pl-5 space-y-2'>
                <li>
                  Output generated by the Service may be inaccurate, harmful, or
                  misleading.
                </li>
                <li>
                  The Service should not be relied upon for medical, legal,
                  financial, or professional decision-making.
                </li>
                <li>
                  Press0 makes no guarantees regarding the accuracy or
                  suitability of responses.
                </li>
              </ul>
              <p>
                Your use of any generated content is solely at your own risk.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Limitation of Liability
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                To the maximum extent permitted by law, Press0, its directors,
                employees, partners, suppliers, and affiliates shall not be
                liable for any direct, indirect, incidental, consequential, or
                punitive damages, including loss of data, profits, revenue,
                business opportunities, or goodwill, arising out of or related
                to:
              </p>
              <ul className='list-disc pl-5 space-y-2'>
                <li>Use or inability to use the Service</li>
                <li>Reliance on AI-generated content</li>
                <li>Unauthorized access to or use of your WhatsApp account</li>
                <li>Service outages or third-party failures</li>
              </ul>
              <p>
                In no event shall Press&apos;s total aggregate liability exceed
                the amount paid by you (if any) in the 12 months preceding the
                claim.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Termination
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                Press0 may suspend or terminate your access to the Service at
                any time, with or without notice, for any reason, including
                suspected misuse or violation of these Terms.
              </p>
              <p>
                Upon termination, all rights granted to you under these Terms
                shall cease immediately.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Changes to Terms
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                Press0 reserves the right to modify or replace these Terms at
                any time. Material changes will be communicated via our website
                or other reasonable means.
              </p>
              <p>
                Your continued use of the Service after updated Terms become
                effective constitutes acceptance of the revised Terms.
              </p>
            </div>
          </section>

          <Separator />
          <section className='flex flex-col gap-4'>
            <h2 className='text-2xl sm:text-3xl font-semibold tracking-tight'>
              Contact Information
            </h2>
            <div className='flex flex-col gap-3 text-muted-foreground leading-relaxed'>
              <p>
                If you have any questions regarding these Terms, please contact
                us through our support channels or via email.
              </p>
              <p className='text-sm text-muted-foreground/80'>
                Last updated: {date}
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditionsPage;
